name: work

type: rails

up:
  - homebrew:
    - openssl
    - shopify/shopify/mysql-client:
        or:        [mysql]
        conflicts: [mysql-connector-c]
    # - another_package
  - ruby: 2.5.3
  - bundler
  - railgun
  - database:
      bootstrap: bin/rails db:create db:migrate db:schema:load
      migrate: bin/rails db:migrate db:test:prepare
      host: work.railgun
      user: root
      password: ''
      database: work_development

server:
  port: 54592

commands:
  console: bin/rails console
  test:
    syntax:
      argument: file
      optional: args...
    run:    bin/rails test

# These use fuzzy-matching, so you can (e.g.) `dev open app`
open:
  "My Application": https://work.myshopify.io
  #ops:
    # - https://datadog.link
    # - https://bugsnag.link
    # - https://kafka.link
